Import('env')

build  = env['CONFIG']['global']['build']['plot']
source = env['CONFIG']['global']['source']['plot']
data   = env['CONFIG']['global']['build']['draw_data']

env.BuildPython(target  = ['#%s/draw_plot.eps'       % build,
                           '#%s/draws.csv'      % build],
                source  = ['#%s/plot.py' % source,
                           '#%s/draws.csv'       % data],
                log_ext = 'plot')

env.Install('#release', '#%s/' % build)

